/**
 * Tests for the app's recommendation rule.
 *
 * The app ports the Python per-roll rule (analysis/rollchance.py) so the
 * morning screen works with no server and no connection. That is a
 * correctness risk: if the two drift, the app shows a number the evidence
 * never scored. `fixtures/roll_chance_cases.json` is generated by the Python
 * implementation, and every case in it is replayed here.
 */

import { describe, expect, it } from "vitest";
import {
  MODEL_VERSION, chanceOf, criticalRatio, delta, effectivePrice, explainRoll, recommendFor,
  toObservations,
} from "./model";
import cases from "./fixtures/roll_chance_cases.json";
import type { Entry, Item } from "./types";

const ITEM: Item = {
  itemId: 1, itemKey: "roll", displayName: "roll",
  price: 10, unitCost: 2.5, sortOrder: 0, active: true,
};

function day(n: number): string {
  const d = new Date(2026, 0, 5); // Monday 2026-01-05
  d.setDate(d.getDate() + n);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

let seq = 0;
function entry(n: number, type: Entry["entryType"], qty: number, itemId = 1): Entry {
  return {
    businessDate: day(n), itemId, entryType: type, quantity: qty,
    mutationId: `m${seq++}`, recordedAt: `2026-01-01T00:00:0${seq % 10}Z`,
  };
}

/** made/wasted for a run of days. */
function history(days: number, made: number, wasted: (i: number) => number): Entry[] {
  const out: Entry[] = [];
  for (let i = 0; i < days; i++) {
    out.push(entry(i, "made", made));
    const w = wasted(i);
    if (w > 0) out.push(entry(i, "waste", w));
  }
  return out;
}

describe("observations", () => {
  it("derives sold as made + refill - wasted", () => {
    const obs = toObservations([entry(0, "made", 8), entry(0, "refill", 2), entry(0, "waste", 3)]);
    expect(obs[0]).toMatchObject({ supply: 10, sold: 7, censored: false });
  });

  it("marks a day with no waste as censored", () => {
    const obs = toObservations([entry(0, "made", 10)]);
    expect(obs[0]).toMatchObject({ sold: 10, censored: true });
  });

  it("clamps negative demand, which means a refill went unrecorded", () => {
    const obs = toObservations([entry(0, "made", 2), entry(0, "waste", 3)]);
    expect(obs[0].sold).toBe(0);
  });

  it("takes the latest write per field, so corrections apply", () => {
    const a = entry(0, "made", 5);
    const b = { ...entry(0, "made", 9), recordedAt: "2027-01-01T00:00:00Z" };
    expect(toObservations([a, b])[0].supply).toBe(9);
  });

  it("ignores a day where nothing was produced", () => {
    expect(toObservations([entry(0, "waste", 3)])).toHaveLength(0);
  });
});

describe("critical ratio", () => {
  it("is the gross margin ratio when there is no salvage", () => {
    expect(criticalRatio(ITEM, day(0), [])).toBeCloseTo(0.75, 10);
  });

  it("drops on a promo day", () => {
    const wed = day(2);
    expect(criticalRatio(ITEM, wed, [3])).toBeCloseTo(1 - 2.5 / (10 * 2 / 3), 10);
    expect(criticalRatio(ITEM, wed, [3])!).toBeLessThan(criticalRatio(ITEM, day(0), [3])!);
  });

  it("is null when cost is missing or exceeds price", () => {
    expect(criticalRatio({ ...ITEM, unitCost: null }, day(0))).toBeNull();
    expect(criticalRatio({ ...ITEM, unitCost: 12 }, day(0))).toBeNull();
  });
});

describe("matches the Python implementation", () => {
  // Every case below was computed by analysis/rollchance.py. A stale file
  // fails the Python suite; a drifted port fails here.
  interface Case {
    name: string; date: string; price: number; unitCost: number;
    promoWeekdays?: number[]; labour?: number; share?: number; ambition?: number;
    days: { date: string; made: number; waste: number }[];
    expected: { breakEven: number | null; chances: number[]; quantity: number | null;
                recentMax: number; testing: boolean; base: number | null;
                climb: { steps: number; days: number; soldOut: number; popularity: number;
                         continuation: number; confidence: number } | null };
  }

  it("is testing the same rule version", () => {
    expect(cases.version).toBe(MODEL_VERSION);
  });

  for (const c of cases.cases as Case[]) {
    it(`agrees on: ${c.name}`, () => {
      const item: Item = { ...ITEM, price: c.price, unitCost: c.unitCost };
      const entries: Entry[] = [];
      c.days.forEach((x, i) => {
        entries.push({ businessDate: x.date, itemId: 1, entryType: "made", quantity: x.made,
                       mutationId: `p${i}m`, recordedAt: "2026-01-01T00:00:00Z" });
        if (x.waste > 0) {
          entries.push({ businessDate: x.date, itemId: 1, entryType: "waste", quantity: x.waste,
                         mutationId: `p${i}w`, recordedAt: "2026-01-01T00:00:00Z" });
        }
      });
      const rec = recommendFor(c.date, [item], null, entries, {
        promoWeekdays: c.promoWeekdays ?? [], promoMultiplier: 2 / 3,
        labourPerRoll: c.labour ?? 0, saleShare: c.share ?? 1, ambition: c.ambition ?? 3,
      }).recommendations[0];
      expect(rec.modelQty).toBe(c.expected.quantity);
      expect(rec.ruleQty).toBe(c.expected.base);
      if (c.expected.climb === null) expect(rec.climb).toBeNull();
      else {
        const x = c.expected.climb;
        expect(rec.climb).toMatchObject({ steps: x.steps, days: x.days, soldOut: x.soldOut,
                                          continuation: x.continuation });
        expect(rec.climb!.popularity).toBeCloseTo(x.popularity, 12);
        expect(rec.climb!.confidence).toBeCloseTo(x.confidence, 12);
      }
      expect(rec.recentMax).toBe(c.expected.recentMax);
      expect(rec.testing).toBe(c.expected.testing);
      if (c.expected.breakEven === null) expect(rec.breakEven).toBeNull();
      else expect(rec.breakEven!).toBeCloseTo(c.expected.breakEven, 12);
      expect(rec.chances).toHaveLength(c.expected.chances.length);
      c.expected.chances.forEach((p, k) => expect(rec.chances![k]).toBeCloseTo(p, 12));
    });
  }
});

describe("recommendations", () => {
  it("never sees the day it is planning for", () => {
    const past = history(40, 10, () => 2);
    const poisoned = [...past, entry(40, "made", 999)];
    const a = recommendFor(day(40), [ITEM], null, past, []);
    const b = recommendFor(day(40), [ITEM], null, poisoned, []);
    expect(a.recommendations).toEqual(b.recommendations);
  });

  it("reads a sell-out as 'at least' and tests one more", () => {
    // Made 3, sold all 3, every day for six weeks: demand is at least 3.
    const set = recommendFor(day(42), [ITEM], null, history(42, 3, () => 0), []);
    const rec = set.recommendations[0];
    expect(rec.modelQty).toBe(4);
    expect(rec.testing).toBe(true);
    expect(rec.reason).toMatch(/^testing a 4th/);
  });

  it("does not test above a ceiling that came back with leftovers", () => {
    const set = recommendFor(day(42), [ITEM], null, history(42, 3, () => 1), []);
    expect(set.recommendations[0].modelQty).toBeLessThanOrEqual(3);
    expect(set.recommendations[0].testing).toBe(false);
  });

  it("always carries the naive baseline, per the Phase 5 brief", () => {
    const set = recommendFor(day(40), [ITEM], null, history(40, 10, () => 2), []);
    expect(set.recommendations[0].naiveBaselineQty).not.toBeNull();
  });

  it("has no opinion on an item with under a week on record", () => {
    const set = recommendFor(day(6), [ITEM], null, history(6, 10, () => 2), []);
    expect(set.recommendations[0].modelQty).toBeNull();
    expect(delta(set.recommendations[0])).toBeNull();
    expect(set.recommendations[0].caveat).toMatch(/fewer than 7 days/);
  });

  it("never gives high confidence to an item that sells out most days", () => {
    const set = recommendFor(day(70), [ITEM], null, history(70, 10, () => 0), []);
    expect(set.recommendations[0].confidence).toBe("low");
  });

  it("gives high confidence to a long clean history", () => {
    const set = recommendFor(day(70), [ITEM], null, history(70, 10, () => 3), []);
    expect(set.recommendations[0].confidence).toBe("high");
  });

  it("cites the leftovers and the chance of one more behind a trim", () => {
    const set = recommendFor(day(40), [ITEM], null, history(40, 10, () => 6), []);
    expect(set.recommendations[0].reason).toMatch(/^\d+ left in \d+ days · \d+(st|nd|rd|th) ~\d+%$/);
  });

  it("quotes the chance against the break-even otherwise", () => {
    // Sells out two days in five: not enough for the climber to act on, and
    // not enough leftovers to be described as a trim.
    const set = recommendFor(day(40), [ITEM], null, history(40, 10, (i) => i % 5 < 2 ? 0 : 1), []);
    expect(set.recommendations[0].reason).toMatch(/needs 25%$/);
  });

  it("keeps every reason short enough to render on one line", () => {
    // These sit in a 340px column on a phone. Past roughly 44 characters the
    // ellipsis starts eating the numbers, which is the only reason to print
    // the line at all.
    for (const h of [history(40, 10, () => 6), history(40, 10, () => 0),
                     history(40, 10, () => 3), history(3, 10, () => 3),
                     history(40, 12, (i) => i % 3)]) {
      for (const rec of recommendFor(day(40), [ITEM], null, h, []).recommendations) {
        expect(rec.reason!.length).toBeLessThanOrEqual(44);
      }
    }
  });

  it("flags a promo day at set level and lists heavy sellers", () => {
    const wed = day(30);
    const set = recommendFor(wed, [ITEM], null, history(30, 10, () => 0), [3]);
    expect(set.notes.some((n) => n.includes("Buy-2-get-1"))).toBe(true);
    expect(set.notes.some((n) => n.includes("sell out most days"))).toBe(true);
  });

  it("explains itself, and no longer claims to be a stand-in", () => {
    const set = recommendFor(day(40), [ITEM], null, history(40, 10, () => 2), []);
    expect(set.degraded).toBe(false);
    expect(set.notes.at(-1)).toMatch(/chance of selling beats its break-even/);
  });

  it("computes the delta against the operator's own template", () => {
    const set = recommendFor(day(40), [ITEM], { quantities: { 1: 3 } },
                             history(40, 10, () => 2), []);
    const rec = set.recommendations[0];
    expect(rec.baselineQty).toBe(3);
    expect(delta(rec)).toBe(rec.modelQty! - 3);
  });

  it("is deterministic", () => {
    const h = history(50, 10, (i) => i % 4);
    expect(recommendFor(day(50), [ITEM], null, h, []))
      .toEqual(recommendFor(day(50), [ITEM], null, h, []));
  });

  it("raises the bar when labour and the store's cut are counted", () => {
    const h = history(42, 8, (i) => i % 5);
    const plain = recommendFor(day(42), [ITEM], null, h, {}).recommendations[0];
    const costly = recommendFor(day(42), [ITEM], null, h,
                                { labourPerRoll: 1, saleShare: 0.75 }).recommendations[0];
    expect(costly.breakEven!).toBeCloseTo(3.5 / 7.5, 10);
    expect(costly.modelQty!).toBeLessThanOrEqual(plain.modelQty!);
  });
});

describe("ambition", () => {
  // Made 4 for a week, sold out on all but one day: a popular item that
  // keeps running out. The base rule stays at 4; any more is the climber.
  const hot = [...history(35, 3, () => 0),
               ...Array.from({ length: 7 }, (_, i) => i + 35).flatMap((n) =>
                 n % 5 ? [entry(n, "made", 4)] : [entry(n, "made", 4), entry(n, "waste", 1)])];
  const pricey: Item = { ...ITEM, price: 8.99, unitCost: 2.03 };
  const at = (ambition: number) =>
    recommendFor(day(42), [pricey], null, hot, { ambition, saleShare: 0.8, promoWeekdays: [] })
      .recommendations[0];

  it("careful never climbs", () => {
    const rec = at(1);
    expect(rec.climbSteps).toBe(0);
    expect(rec.modelQty).toBe(rec.ruleQty);
  });

  it("climbs a popular item that keeps selling out, more at higher levels", () => {
    const steps = [1, 2, 3, 4, 5].map((a) => at(a).climbSteps!);
    expect(steps[2]).toBeGreaterThanOrEqual(1);
    expect(steps).toEqual([...steps].sort((a, b) => a - b));
    expect(at(3).reason).toMatch(/^climbing \+\d · sold out \d+ of last \d+$/);
  });

  it("says why, in the rule's own terms, when you are below it", () => {
    const rec = at(3);
    expect(explainRoll(rec, rec.ruleQty!)).toMatch(/^climbing: sold out \d+ of last \d+ · \d+% sure a \d+(st|nd|rd|th) pays$/);
  });

  it("does not climb on one sell-out of a slow item", () => {
    const slow = [...history(41, 1, () => 1), entry(41, "made", 1)];
    const rec = recommendFor(day(42), [pricey], null, slow, { ambition: 5, saleShare: 0.8 })
      .recommendations[0];
    expect(rec.climbSteps).toBe(0);
  });

  it("names the ambition in the model version and in the day's notes", () => {
    const set = recommendFor(day(42), [pricey], null, hot, { ambition: 4, saleShare: 0.8, promoWeekdays: [] });
    expect(set.recommendations[0].modelVersion).toMatch(/-a4$/);
    expect(set.notes[0]).toMatch(/^Ambition bold: trying \d+ extra roll/);
  });
});

describe("explaining a disagreement", () => {
  const rec = recommendFor(day(42), [ITEM], null, history(42, 6, (i) => 1 + (i % 3)), [])
    .recommendations[0];

  it("says nothing when you agree", () => {
    expect(explainRoll(rec, rec.modelQty!)).toBeNull();
  });

  it("quotes the first roll you left off when the rule wants more", () => {
    const yours = rec.modelQty! - 1;
    const pctOf = Math.round(100 * chanceOf(rec.chances!, yours + 1));
    expect(explainRoll(rec, yours))
      .toMatch(new RegExp(`^a ${yours + 1}(st|nd|rd|th) would sell ${pctOf}% of days · needs 25%$`));
  });

  it("quotes your last roll when the rule wants fewer", () => {
    expect(explainRoll(rec, 9)).toMatch(/^your 9th sells \d+% of days · needs 25%$/);
  });

  it("names a test roll as a test", () => {
    const hot = recommendFor(day(42), [ITEM], null, history(42, 3, () => 0), []).recommendations[0];
    expect(explainRoll(hot, 3)).toMatch(/^test a 4th: would sell \d+% · needs 25%$/);
  });

  it("extends the ladder exactly past anything ever made", () => {
    const c = rec.chances!;
    expect(chanceOf(c, c.length + 2)).toBeCloseTo(c[c.length - 1] * 0.25, 12);
    expect(chanceOf(c, 0)).toBe(1);
  });
});

describe("quantity floor", () => {
  it("never recommends zero for an item that is being made", () => {
    // Never sells at all; a cheap margin would still leave it at zero.
    const cheapMargin: Item = { ...ITEM, price: 10, unitCost: 6 };
    const entries: Entry[] = [];
    for (let w = 0; w < 8; w++) {
      entries.push(entry(w * 7, "made", 1));
      entries.push(entry(w * 7, "waste", 1));
    }
    const set = recommendFor(day(56), [cheapMargin], null, entries, []);
    expect(set.recommendations[0].modelQty).toBe(1);
  });

  it("leaves an item that is never made at zero", () => {
    const entries: Entry[] = [];
    for (let w = 0; w < 8; w++) entries.push(entry(w * 7, "made", 0));
    const set = recommendFor(day(56), [ITEM], null, entries, []);
    expect(set.recommendations[0].modelQty).toBe(0);
  });

  it("carries every setting in the model version, so stored recs stay attributable", () => {
    const set = recommendFor(day(40), [ITEM], null, history(40, 10, () => 2), []);
    expect(set.recommendations[0].modelVersion).toBe("2.1.0-o0.3-h3-p0.5-m5/1@0.9-s1-f1-c8/3-a3");
  });
});

describe("effective price and promotions", () => {
  const base: Item = {
    itemId: 1, itemKey: "cali", displayName: "cali roll", price: 7.99,
    unitCost: 1.6, sortOrder: 0, active: true,
  };
  const WED = "2026-09-23";   // a Wednesday
  const THU = "2026-09-24";

  it("uses the normal price on a normal day", () => {
    expect(effectivePrice(base, THU)).toBe(7.99);
  });

  it("applies the store-wide multiplier on a promo weekday", () => {
    expect(effectivePrice(base, WED)).toBeCloseTo(7.99 * 2 / 3, 4);
  });

  it("lets a flat item promo price win outright, without stacking", () => {
    // $5.99 means $5.99. Stacking buy-2-get-1 on top would make it $3.99 and
    // halve the target quantity for no reason the operator would recognise.
    const promo = { ...base, promoPrice: 5.99, promoWeekdays: [3] };
    expect(effectivePrice(promo, WED)).toBe(5.99);
  });

  it("ignores a promo price on a day it does not apply", () => {
    const promo = { ...base, promoPrice: 5.99, promoWeekdays: [3] };
    expect(effectivePrice(promo, THU)).toBe(7.99);
  });

  it("lowers the target quantile when the price drops", () => {
    // The point of the whole thing: a discount is a thinner margin, which is
    // LESS tolerance for binning a unit, so the model should make fewer.
    const full = criticalRatio(base, THU)!;
    const promo = criticalRatio({ ...base, promoPrice: 5.99, promoWeekdays: [3] }, WED)!;
    expect(full).toBeCloseTo(1 - 1.6 / 7.99, 4);
    expect(promo).toBeCloseTo(1 - 1.6 / 5.99, 4);
    expect(promo).toBeLessThan(full);
  });

  it("refuses a promo price at or below cost", () => {
    const loss = { ...base, promoPrice: 1.5, promoWeekdays: [3] };
    expect(criticalRatio(loss, WED)).toBeNull();
  });
});

describe("uncounted days", () => {
  // Leftovers never counted means no waste rows, and toObservations reads no
  // waste as "sold everything". Handed to the rule raw, a day nobody counted
  // is the best day that item ever had. This is what happened to Tuesdays.
  const mondays = (from: number, to: number, made: number, waste: number | null) => {
    const out: Entry[] = [];
    for (let w = from; w <= to; w++) {
      out.push(entry(w * 7, "made", made));
      if (waste !== null) out.push(entry(w * 7, "waste", waste));
    }
    return out;
  };
  const counted = mondays(0, 7, 4, 2);          // eight counted Mondays: sold 2
  const uncounted = mondays(8, 10, 20, null);   // three big Mondays nobody counted
  const countedDates = new Set(counted.map((e) => e.businessDate));
  const plan = day(11 * 7);

  it("inflates the rule when uncounted days are let in (the bug, shown)", () => {
    const clean = recommendFor(plan, [ITEM], null, counted, []);
    const naive = recommendFor(plan, [ITEM], null, [...counted, ...uncounted], []);
    expect(naive.recommendations[0].modelQty!)
      .toBeGreaterThan(clean.recommendations[0].modelQty!);
  });

  it("leaves them out entirely when told which days were counted", () => {
    const clean = recommendFor(plan, [ITEM], null, counted, []);
    const fixed = recommendFor(plan, [ITEM], null, [...counted, ...uncounted],
                               { counted: countedDates });
    expect(fixed.recommendations[0]).toEqual(clean.recommendations[0]);
  });
});
