import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import * as cloud from "./lib/cloud";
import * as store from "./lib/store";
import "./styles.css";

async function boot() {
  // Seed the item list and any saved templates on first run. Generated by
  // tools/export_web_seed.py; absent until you run it, and the app says so.
  try {
    const seed = await import("./data/seed.json");
    await store.seedIfEmpty(seed.items, seed.templates ?? [], seed.assignments ?? []);
  } catch {
    /* no seed yet */
  }
  // The other half of the seed: the trading history the workbook already held.
  // Kept out of the bundle and fetched once, because it is 72kB the app does
  // not need on any load after the first. Gated on its own marker rather than
  // on the item list, so an install that already has the menu still picks it
  // up. Failure is silent by design -- an app that will not start because a
  // historical file is missing is worse than one that starts without history.
  try {
    if (!(await store.historyImportedAt())) {
      const res = await fetch("/history.json", { cache: "no-store" });
      if (res.ok) await store.importHistory(await res.json());
    }
  } catch {
    /* no history file, or offline on first run -- the app works without it */
  }
  // Wire sync if a project is configured, and finish a magic-link redirect
  // before first render so the app never flashes a signed-out state.
  cloud.completeSignInFromUrl();
  cloud.install();
  if (cloud.isSignedIn()) void cloud.pull().catch(() => {});

  createRoot(document.getElementById("root")!).render(
    <StrictMode><App /></StrictMode>,
  );
}

void boot();

// Offline shell. Registered after boot so a failing service worker can never
// stop the app rendering -- the kiosk needs the screen more than the cache.
if ("serviceWorker" in navigator && import.meta.env.PROD) {
  window.addEventListener("load", () => {
    void navigator.serviceWorker.register("/sw.js").catch(() => {});
  });
}
