"""Censored Poisson regression.

Why this exists, when Phase 4 was specified as quantile regression.

Powell's censored quantile regression only learns from observations whose fitted
quantile sits BELOW that day's censoring limit. Here the limit is the quantity
actually supplied, and supply has been sitting at roughly the median of demand
(49% of item-days sold out). So for a critical ratio near 0.75, almost every
observation lies above the frontier and there is nothing left to fit. That is
not a bug in the estimator -- it is the estimator correctly reporting that the
target is not identified from this data.

    You cannot learn how much more you should have made,
    from data generated by making that much.

A parametric count model breaks the deadlock by borrowing strength from an
assumed shape. Fit the conditional MEAN, which censored observations do inform
(each contributes P(Y >= c), a real constraint on lambda), then read the tail
off the assumed distribution. The price is an assumption -- demand is Poisson
given the covariates -- which is stated, testable, and checked below.

Log-likelihood, with lambda_i = exp(x_i'b):

    uncensored (waste was observed, so demand is known exactly)
        log P(Y = y_i)
    censored (sold out at c_i, so all we know is demand >= c_i)
        log P(Y >= c_i) = log sf(c_i - 1; lambda_i)

Gradients are analytic. For the censored term this uses the identity
d/dlambda P(Y >= c) = pmf(c - 1; lambda), which is what keeps the fit fast and
stable enough to refit weekly inside a walk-forward backtest.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import minimize
from scipy.stats import poisson

#: exp() of anything larger overflows long before it is a plausible sushi count.
_MAX_ETA = 20.0


@dataclass(frozen=True)
class PoissonFit:
    coef: np.ndarray
    n_observations: int
    n_censored: int
    n_parameters: int
    converged: bool
    loglik: float

    @property
    def observations_per_parameter(self) -> float:
        return self.n_observations / self.n_parameters if self.n_parameters else 0.0

    def rate(self, X: np.ndarray) -> np.ndarray:
        eta = np.clip(_with_intercept(X) @ self.coef, -_MAX_ETA, _MAX_ETA)
        return np.exp(eta)

    def quantile(self, X: np.ndarray, tau: float) -> np.ndarray:
        """The tau-quantile of predicted demand -- the newsvendor answer."""
        return poisson.ppf(tau, self.rate(X))


def _with_intercept(X: np.ndarray) -> np.ndarray:
    X = np.asarray(X, dtype=float)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    return np.hstack([np.ones((X.shape[0], 1)), X])


def fit_censored_poisson(
    X: np.ndarray,
    y: np.ndarray,
    censored: np.ndarray,
    *,
    ridge: float = 1e-3,
    max_iterations: int = 300,
) -> PoissonFit:
    """Maximum likelihood with right-censored counts.

    `y` is the observed count: exact demand where `censored` is False, and the
    supply level (a lower bound on demand) where it is True.

    `ridge` is an L2 penalty on the slopes only. With item dummies and few
    observations per item some columns are near-collinear, and without it the
    likelihood has flat directions the optimiser will wander along.
    """
    Z = _with_intercept(X)
    y = np.asarray(y, dtype=float).ravel()
    cens = np.asarray(censored, dtype=bool).ravel()
    if not (len(y) == len(cens) == Z.shape[0]):
        raise ValueError("X, y and censored must have the same length")
    if len(y) == 0:
        raise ValueError("no observations")
    if np.any(y < 0):
        raise ValueError("counts must be non-negative")

    n, p = Z.shape
    penalty = np.ones(p) * ridge
    penalty[0] = 0.0  # never penalise the intercept

    obs_mean = max(y.mean(), 1e-3)
    start = np.zeros(p)
    start[0] = np.log(obs_mean)

    def negative_loglik(b: np.ndarray) -> tuple[float, np.ndarray]:
        eta = np.clip(Z @ b, -_MAX_ETA, _MAX_ETA)
        lam = np.exp(eta)
        grad = np.zeros(p)
        ll = 0.0

        u = ~cens
        if u.any():
            ll += float(np.sum(poisson.logpmf(y[u], lam[u])))
            grad += Z[u].T @ (y[u] - lam[u])

        if cens.any():
            c = y[cens]
            lam_c = lam[cens]
            # P(Y >= c) = sf(c - 1); guard the log against exact zero in the
            # far tail, where a censored point is essentially impossible.
            sf = np.clip(poisson.sf(c - 1, lam_c), 1e-300, 1.0)
            ll += float(np.sum(np.log(sf)))
            # d/dlambda P(Y >= c) = pmf(c - 1; lambda)
            dsf = poisson.pmf(c - 1, lam_c)
            grad += Z[cens].T @ (dsf / sf * lam_c)

        ll -= float(np.sum(penalty * b * b))
        grad -= 2.0 * penalty * b
        return -ll, -grad

    res = minimize(negative_loglik, start, jac=True, method="L-BFGS-B",
                   options={"maxiter": max_iterations})

    return PoissonFit(
        coef=res.x, n_observations=n, n_censored=int(cens.sum()),
        n_parameters=p, converged=bool(res.success), loglik=float(-res.fun),
    )


def dispersion_ratio(y: np.ndarray, rate: np.ndarray) -> float:
    """Pearson dispersion. 1.0 means Poisson fits; above ~1.5 it does not.

    The Poisson assumption forces variance to equal the mean, which is what lets
    the model extrapolate above the observed supply. If demand is overdispersed
    the fitted tail is too thin and recommendations come out too low -- so this
    number belongs in the report, not in a docstring nobody reads.
    """
    y = np.asarray(y, dtype=float)
    rate = np.clip(np.asarray(rate, dtype=float), 1e-9, None)
    return float(np.mean((y - rate) ** 2 / rate))
